### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [Fandroid745/Open-notes#6]
```
META-INF/version-control-info.textproto

4c4

< revision: "be221219bbd16ba815de4db7a796dab95fe4b5ea"

---

> revision: "2ca6ab04300fb1b2976fb33203fab38b3cf5aadf"
```

When you are ready to release, after you tag, you build a fresh APK from the tagged commit checkout. Don't use an old APK...

**Comment by Fandroid745** [comment]
I have updated the metadata.yml with the correct commit hash for 1.3.1 now.

**Comment by licaon-kter** [comment]
Thanks

**Comment by IzzySoft** [comment]
Looks like v1.3.2 has the wrong APK attached, it identifies as

    package: name='com.opennotes' versionCode='4' versionName='1.3'

and RB fails of course with a massive diff. Can you please check and fix? Thanks in advance!

**Comment by Fandroid745** [comment]
I have pushed the corrected apk now.
Thanks!!

**Comment by licaon-kter** [comment]
Not fixed :( https://gitlab.com/fdroid/checkupdates-bot-fdroiddata/-/jobs/11750877381#L382

**Comment by IzzySoft** [comment]
Confirmed here as well, thanks!
